// noinspection ES6PreferShortImport
'use server';

/**
 * @fileOverview An AI agent that generates images from a text prompt.
 *
 * - generateImageFromPrompt - A function that generates an image based on a text prompt.
 * - GenerateImageFromPromptInput - The input type for the generateImageFromPrompt function.
 * - GenerateImageFromPromptOutput - The return type for the generateImageFromPrompt function.
 */

import { z } from 'zod';

const GenerateImageFromPromptInputSchema = z.object({
  prompt: z.string().describe('The text prompt to use to generate the image.'),
});
export type GenerateImageFromPromptInput = z.infer<typeof GenerateImageFromPromptInputSchema>;

const GenerateImageFromPromptOutputSchema = z.object({
  image: z
    .string()
    .describe(
      'The generated image as a data URI that must include a MIME type and use Base64 encoding. Expected format: \'data:<mimetype>;base64,<encoded_data>\'.'
    ),
});
export type GenerateImageFromPromptOutput = z.infer<typeof GenerateImageFromPromptOutputSchema>;

export async function generateImageFromPrompt(
  input: GenerateImageFromPromptInput
): Promise<GenerateImageFromPromptOutput> {
  const parsedInput = GenerateImageFromPromptInputSchema.parse(input);

  const stabilityApiKey = process.env.STABILITY_API_KEY;

  if (!stabilityApiKey) {
    throw new Error('STABILITY_API_KEY is not set in environment variables');
  }

  const engineId = 'stable-diffusion-xl-1024-v1-0';
  const apiHost = 'https://api.stability.ai';

  const response = await fetch(
    `${apiHost}/v1/generation/${engineId}/text-to-image`,
    {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Accept: 'application/json',
        Authorization: `Bearer ${stabilityApiKey}`,
      },
      body: JSON.stringify({
        text_prompts: [
          {
            text: parsedInput.prompt,
          },
        ],
        cfg_scale: 7,
        height: 1024,
        width: 1024,
        steps: 30,
        samples: 1,
      }),
    }
  );

  if (!response.ok) {
    const errorText = await response.text();
    throw new Error(`Stability AI Error (${response.status}): ${errorText}`);
  }

  const responseJSON = await response.json();

  if (!responseJSON.artifacts || responseJSON.artifacts.length === 0) {
    throw new Error('No image generated by Stability AI');
  }

  const base64Image = responseJSON.artifacts[0].base64;
  const output = { image: `data:image/png;base64,${base64Image}` };
  return GenerateImageFromPromptOutputSchema.parse(output);
}